option(BUFFETALLIGATOR_ENABLE_GPU_ALLOCATORS "Build the optional GPU buffer allocators" OFF)
target_compile_definitions(alligator PUBLIC
    BUFFETALLIGATOR_ENABLE_GPU_ALLOCATORS=$<BOOL:${BUFFETALLIGATOR_ENABLE_GPU_ALLOCATORS}>)
if(NOT BUFFETALLIGATOR_ENABLE_GPU_ALLOCATORS)
    set(BUFFETALLIGATOR_ENABLE_VULKAN OFF)
    set(BUFFETALLIGATOR_ENABLE_METAL OFF)
    set(BUFFETALLIGATOR_ENABLE_CUDA OFF)
    return()
endif()
option(BUFFETALLIGATOR_ENABLE_VULKAN "Build the Vulkan allocator" ON)
option(BUFFETALLIGATOR_ENABLE_METAL "Build the Metal allocator" ${APPLE})
find_package(CUDAToolkit QUIET)
option(BUFFETALLIGATOR_ENABLE_CUDA "Build the CUDA allocator" ${CUDAToolkit_FOUND})
if(BUFFETALLIGATOR_ENABLE_METAL)
    if(NOT APPLE)
        message(FATAL_ERROR "Metal requires macOS; configure with -DBUFFETALLIGATOR_ENABLE_METAL=OFF")
    endif()
    enable_language(OBJCXX)
    set(CMAKE_OBJCXX_STANDARD 20)
    set(CMAKE_OBJCXX_STANDARD_REQUIRED ON)
    target_sources(alligator PRIVATE src/memory/metal_allocator.mm)
    set_source_files_properties(src/memory/metal_allocator.mm PROPERTIES COMPILE_OPTIONS -fobjc-arc)
    target_compile_definitions(alligator PUBLIC BUFFETALLIGATOR_HAS_METAL=1)
    target_link_libraries(alligator PUBLIC "-framework Metal" "-framework Foundation")
endif()
if(BUFFETALLIGATOR_ENABLE_CUDA)
    if(NOT CUDAToolkit_FOUND)
        message(FATAL_ERROR "CUDA allocator needs the NVIDIA CUDA Toolkit; set CUDAToolkit_ROOT to its installation")
    endif()
    target_sources(alligator PRIVATE src/memory/cuda_allocator.cpp)
    target_compile_definitions(alligator PUBLIC BUFFETALLIGATOR_HAS_CUDA=1)
    target_link_libraries(alligator PUBLIC CUDA::cuda_driver)
endif()
if(BUFFETALLIGATOR_ENABLE_VULKAN)
    if(APPLE)
        set(BUFFETALLIGATOR_DEFAULT_VULKAN_RUNTIME "${BUFFETALLIGATOR_DEPS_DIR}/MoltenVK/lib/libMoltenVK.dylib")
    else()
        set(BUFFETALLIGATOR_DEFAULT_VULKAN_RUNTIME "${BUFFETALLIGATOR_DEPS_DIR}/vulkan-loader/lib/libvulkan.so.1")
    endif()
    set(BUFFETALLIGATOR_VULKAN_RUNTIME "${BUFFETALLIGATOR_DEFAULT_VULKAN_RUNTIME}" CACHE FILEPATH "Vulkan runtime library")
    get_filename_component(BUFFETALLIGATOR_VULKAN_FILENAME "${BUFFETALLIGATOR_VULKAN_RUNTIME}" NAME)
    if(NOT EXISTS "${BUFFETALLIGATOR_VULKAN_RUNTIME}")
        message(FATAL_ERROR "Vulkan runtime is missing; run ./run_build.sh -DBUFFETALLIGATOR_ENABLE_GPU_ALLOCATORS=ON to prepare it")
    endif()
    add_library(alligator::vulkan SHARED IMPORTED GLOBAL)
    set_target_properties(alligator::vulkan PROPERTIES
        IMPORTED_LOCATION "${BUFFETALLIGATOR_VULKAN_RUNTIME}"
        INTERFACE_INCLUDE_DIRECTORIES "${BUFFETALLIGATOR_DEPS_DIR}/vulkan-headers/include")
    target_sources(alligator PRIVATE src/memory/vulkan_allocator.cpp)
    target_compile_definitions(alligator PUBLIC BUFFETALLIGATOR_HAS_VULKAN=1)
    target_link_libraries(alligator PUBLIC alligator::vulkan)
    file(REAL_PATH "${BUFFETALLIGATOR_VULKAN_RUNTIME}" BUFFETALLIGATOR_VULKAN_REAL_RUNTIME)
    install(FILES "${BUFFETALLIGATOR_VULKAN_REAL_RUNTIME}" DESTINATION ${CMAKE_INSTALL_LIBDIR}/alligator
        RENAME "${BUFFETALLIGATOR_VULKAN_FILENAME}")
    install(DIRECTORY "${BUFFETALLIGATOR_DEPS_DIR}/vulkan-headers/include/vulkan"
        "${BUFFETALLIGATOR_DEPS_DIR}/vulkan-headers/include/vk_video" DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})
endif()
