# Imported dependency targets are recreated relative to the installation prefix for consumers.
include(GNUInstallDirs)
find_package(PkgConfig REQUIRED)
set(ENV{PKG_CONFIG_PATH} "${BUFFETALLIGATOR_DEPS_DIR}/libfabric/lib/pkgconfig:$ENV{PKG_CONFIG_PATH}")
pkg_check_modules(ALLIGATOR_FABRIC REQUIRED libfabric)
set(BUFFETALLIGATOR_FABRIC_LIBRARIES ${ALLIGATOR_FABRIC_STATIC_LIBRARIES})
list(REMOVE_ITEM BUFFETALLIGATOR_FABRIC_LIBRARIES fabric pthread dl)
list(REMOVE_DUPLICATES BUFFETALLIGATOR_FABRIC_LIBRARIES)
foreach(dependency IN ITEMS uv sodium fabric)
    if(dependency STREQUAL uv)
        set(prefix libuv)
    elseif(dependency STREQUAL sodium)
        set(prefix libsodium)
    else()
        set(prefix libfabric)
    endif()
    set(archive "${BUFFETALLIGATOR_DEPS_DIR}/${prefix}/lib/lib${dependency}.a")
    if(NOT EXISTS "${archive}")
        message(FATAL_ERROR "${prefix} is missing; run ./run_build.sh to fetch and build dependencies")
    endif()
    add_library(alligator::${dependency} STATIC IMPORTED GLOBAL)
    set_target_properties(alligator::${dependency} PROPERTIES
        IMPORTED_LOCATION "${archive}"
        INTERFACE_INCLUDE_DIRECTORIES "${BUFFETALLIGATOR_DEPS_DIR}/${prefix}/include")
    install(FILES "${archive}" DESTINATION "${CMAKE_INSTALL_LIBDIR}/alligator")
endforeach()
set_property(TARGET alligator::uv PROPERTY INTERFACE_LINK_LIBRARIES "Threads::Threads;${CMAKE_DL_LIBS}")
if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set_property(TARGET alligator::uv APPEND PROPERTY INTERFACE_LINK_LIBRARIES rt m)
endif()
set_property(TARGET alligator::fabric PROPERTY INTERFACE_LINK_LIBRARIES
    "Threads::Threads;${CMAKE_DL_LIBS};${BUFFETALLIGATOR_FABRIC_LIBRARIES}")
set_property(TARGET alligator::fabric PROPERTY INTERFACE_LINK_DIRECTORIES
    "${ALLIGATOR_FABRIC_STATIC_LIBRARY_DIRS}")
foreach(dependency IN ITEMS libuv libsodium libfabric)
    file(GLOB notices "${BUFFETALLIGATOR_DEPS_SOURCE_DIR}/${dependency}/LICENSE*"
        "${BUFFETALLIGATOR_DEPS_SOURCE_DIR}/${dependency}/COPYING*")
    foreach(notice IN LISTS notices)
        if(IS_DIRECTORY "${notice}")
            install(DIRECTORY "${notice}" DESTINATION "${CMAKE_INSTALL_DATADIR}/licenses/alligator/${dependency}")
        else()
            install(FILES "${notice}" DESTINATION "${CMAKE_INSTALL_DATADIR}/licenses/alligator/${dependency}")
        endif()
    endforeach()
endforeach()
