foreach(required IN ITEMS ALLIGATOR_BUILD_DIR ALLIGATOR_SOURCE_DIR ALLIGATOR_CONSUMER_SOURCE_DIR
        ALLIGATOR_PACKAGE_CMAKEDIR ALLIGATOR_INSTALL_INCLUDEDIR ALLIGATOR_GENERATOR
        ALLIGATOR_CXX_COMPILER)
    if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
        message(FATAL_ERROR "The installed consumer check requires ${required}")
    endif()
endforeach()
if(DEFINED ENV{TMPDIR} AND NOT "$ENV{TMPDIR}" STREQUAL "")
    set(temporary_root "$ENV{TMPDIR}")
elseif(DEFINED ENV{TEMP} AND NOT "$ENV{TEMP}" STREQUAL "")
    set(temporary_root "$ENV{TEMP}")
elseif(CMAKE_HOST_UNIX)
    set(temporary_root /tmp)
else()
    message(FATAL_ERROR "Set TEMP to a writable temporary directory for the installed consumer check")
endif()
string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef unique_suffix)
set(workspace "${temporary_root}/alligator-installed-consumer-${unique_suffix}")
set(original_prefix "${workspace}/original")
set(relocated_prefix "${workspace}/relocated")
set(consumer_source "${workspace}/consumer")
set(consumer_build "${workspace}/build")
file(MAKE_DIRECTORY "${workspace}")
file(COPY "${ALLIGATOR_CONSUMER_SOURCE_DIR}/" DESTINATION "${consumer_source}")
set(install_arguments --install "${ALLIGATOR_BUILD_DIR}" --prefix "${original_prefix}")
if(NOT "${ALLIGATOR_CONFIGURATION}" STREQUAL "")
    list(APPEND install_arguments --config "${ALLIGATOR_CONFIGURATION}")
endif()
message(STATUS "Installing Alligator into a temporary prefix")
execute_process(COMMAND "${CMAKE_COMMAND}" ${install_arguments}
    RESULT_VARIABLE result TIMEOUT 60)
if(NOT "${result}" STREQUAL "0")
    message(FATAL_ERROR "Alligator installation failed; see the CTest output above; workspace: ${workspace}")
endif()
message(STATUS "Moving the complete installation to a second prefix")
file(RENAME "${original_prefix}" "${relocated_prefix}")
if(EXISTS "${original_prefix}")
    message(FATAL_ERROR "The original installation prefix still exists: ${original_prefix}")
endif()
file(GLOB_RECURSE package_files "${relocated_prefix}/*.cmake")
foreach(package_file IN LISTS package_files)
    file(READ "${package_file}" package_contents)
    foreach(forbidden IN ITEMS "${ALLIGATOR_SOURCE_DIR}" "${ALLIGATOR_BUILD_DIR}" "${original_prefix}")
        string(FIND "${package_contents}" "${forbidden}" position)
        if(NOT position EQUAL -1)
            message(FATAL_ERROR "Installed package ${package_file} references its original location: ${forbidden}")
        endif()
    endforeach()
endforeach()
set(configure_arguments -S "${consumer_source}" -B "${consumer_build}" -G "${ALLIGATOR_GENERATOR}"
    "-DCMAKE_CXX_COMPILER=${ALLIGATOR_CXX_COMPILER}" -DCMAKE_BUILD_TYPE=Release
    "-DCMAKE_CXX_FLAGS=${ALLIGATOR_CONSUMER_CXX_FLAGS}"
    "-DCMAKE_PREFIX_PATH=${relocated_prefix}" -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF
    -DCMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY=OFF -DCMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH=OFF
    "-DALLIGATOR_RELOCATED_PREFIX=${relocated_prefix}"
    "-DALLIGATOR_PACKAGE_CMAKEDIR=${ALLIGATOR_PACKAGE_CMAKEDIR}"
    "-DALLIGATOR_INSTALL_INCLUDEDIR=${ALLIGATOR_INSTALL_INCLUDEDIR}"
    "-DALLIGATOR_EXPECTED_DEFINITIONS=${ALLIGATOR_EXPECTED_DEFINITIONS}")
if(NOT "${ALLIGATOR_GENERATOR_PLATFORM}" STREQUAL "")
    list(APPEND configure_arguments -A "${ALLIGATOR_GENERATOR_PLATFORM}")
endif()
if(NOT "${ALLIGATOR_GENERATOR_TOOLSET}" STREQUAL "")
    list(APPEND configure_arguments -T "${ALLIGATOR_GENERATOR_TOOLSET}")
endif()
message(STATUS "Configuring the consumer using only the relocated Alligator package")
execute_process(COMMAND "${CMAKE_COMMAND}" ${configure_arguments}
    RESULT_VARIABLE result TIMEOUT 60)
if(NOT "${result}" STREQUAL "0")
    message(FATAL_ERROR "Installed consumer configuration failed; see the CTest output above; workspace: ${workspace}")
endif()
message(STATUS "Compiling every public header and linking the installed consumer")
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${consumer_build}" --config Release --parallel
    RESULT_VARIABLE result TIMEOUT 120)
if(NOT "${result}" STREQUAL "0")
    message(FATAL_ERROR "Installed consumer compilation failed; see the CTest output above; workspace: ${workspace}")
endif()
file(GLOB_RECURSE generated_commands "${consumer_build}/*/link.txt")
list(APPEND generated_commands "${consumer_build}/compile_commands.json" "${consumer_build}/build.ninja")
foreach(command_file IN LISTS generated_commands)
    if(EXISTS "${command_file}")
        file(READ "${command_file}" commands)
        foreach(forbidden IN ITEMS "${ALLIGATOR_SOURCE_DIR}" "${ALLIGATOR_BUILD_DIR}" "${original_prefix}")
            string(FIND "${commands}" "${forbidden}" position)
            if(NOT position EQUAL -1)
                message(FATAL_ERROR "Consumer commands in ${command_file} reference ${forbidden}")
            endif()
        endforeach()
    endif()
endforeach()
if(EXISTS "${original_prefix}")
    message(FATAL_ERROR "The original prefix reappeared before the runtime check: ${original_prefix}")
endif()
message(STATUS "Running the relocated consumer with NDEBUG enabled")
execute_process(COMMAND "${CMAKE_COMMAND}" -E env --unset=LD_LIBRARY_PATH
    --unset=DYLD_LIBRARY_PATH --unset=DYLD_FALLBACK_LIBRARY_PATH
    "${CMAKE_CTEST_COMMAND}" --test-dir "${consumer_build}" -C Release --output-on-failure
    RESULT_VARIABLE result TIMEOUT 40)
if(NOT "${result}" STREQUAL "0")
    message(FATAL_ERROR "Installed consumer execution failed; see the CTest output above; workspace: ${workspace}")
endif()
message(STATUS "Installed headers, backend definitions, relocation, and consumer execution passed; workspace: ${workspace}")
